[project]
name = "primitive-db"
version = "1.0.0"
description = "Educational console database with JSON storage"
readme = "README.md"
authors = [
    { name = "Александр Ткачук" }
]
requires-python = ">=3.12"
dependencies = [
    "prettytable>=3.18.0",
    "prompt>=0.4.1",
]

[project.scripts]
project = "primitive_db.main:main"
database = "primitive_db.main:main"

[build-system]
requires = ["hatchling>=1.26"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/primitive_db"]

[tool.ruff]
line-length = 88
target-version = "py312"
exclude = [".venv", "venv", "dist", "__pycache__"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []

[dependency-groups]
dev = [
    "ruff>=0.16.10",
]
